# Generated by Django 5.0 on 2024-01-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
        migrations.RenameModel(
            old_name='Sub_Sub_Category',
            new_name='SubSubCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.ImageField(default=1, upload_to='uploads/category_image'),
            preserve_default=False,
        ),
    ]
