# Generated by Django 5.0 on 2024-01-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_sub_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subsubcategory',
            old_name='category_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
