# Generated by Django 5.0 on 2024-01-04 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_category_name_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category_name',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='sub_category_name',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='sub_sub_category_name',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
