# Generated by Django 5.0 on 2024-01-04 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
            preserve_default=False,
        ),
    ]
