# Generated by Django 5.0 on 2024-01-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_subcategory_title_alter_subsubcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='category.category'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_category', to='category.subcategory'),
        ),
    ]
