# Generated by Django 5.0 on 2024-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_category_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(default=1, upload_to='uploads/category_banner'),
            preserve_default=False,
        ),
    ]
