# Generated by Django 5.0 on 2024-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
