# Generated by Django 5.0 on 2024-02-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_alter_subsubcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Category'},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'verbose_name_plural': 'Sub Sub Category'},
        ),
    ]
