# Generated by Django 5.0 on 2024-02-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='No need to fill out this field', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='No need to fill out this field', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='No need to fill out this field', null=True),
        ),
    ]
