# Generated by Django 5.0 on 2024-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_alter_category_slug_alter_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(upload_to='uploads/category_banner', verbose_name='Upload Category Banner'),
        ),
    ]
