# Generated by Django 5.0 on 2024-02-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='No need to fill out this field', null=True),
        ),
    ]
