# Generated by Django 5.0 on 2024-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvariation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
