# Generated by Django 5.0 on 2024-01-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='multipleimage',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_image', to='product.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/product_image'),
            preserve_default=False,
        ),
    ]
