# Generated by Django 5.0 on 2024-01-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_variantimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
        migrations.AlterField(
            model_name='variantimages',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='product.productvariation'),
        ),
        migrations.CreateModel(
            name='VariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variant', to='product.productvariation')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.size')),
            ],
        ),
    ]
