# Generated by Django 5.0 on 2024-01-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productvariation_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.size'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VariantSize',
        ),
    ]
