# Generated by Django 5.0 on 2024-01-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productvariation_size_delete_variantsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_variant', to='product.productvariation')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.size')),
            ],
        ),
    ]
