# Generated by Django 5.0 on 2024-01-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_pricing_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='size',
        ),
        migrations.AddField(
            model_name='pricing',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_size', to='product.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
