# Generated by Django 5.0 on 2024-01-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_pricing_size_pricing_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='slug',
        ),
    ]
