# Generated by Django 5.0 on 2024-01-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
