# Generated by Django 5.0 on 2024-01-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='product.productvariation'),
        ),
    ]
