# Generated by Django 5.0 on 2024-01-11 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_pricing_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimages',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='selling_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_size', to='product.size'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='VariantImages',
        ),
    ]
