# Generated by Django 5.0 on 2024-01-13 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_variantimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimages',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='variantimages',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_color', to='product.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='product.product'),
            preserve_default=False,
        ),
    ]
