# Generated by Django 5.0 on 2024-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productimages_delete_variantimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
