# Generated by Django 5.0 on 2024-01-16 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_brand_facebook_link_brand_instagram_link_and_more'),
        ('product', '0022_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='brand.brand'),
        ),
    ]
