# Generated by Django 5.0 on 2024-01-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='image',
        ),
    ]
