# Generated by Django 5.0 on 2024-02-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_slug_alter_productvariation_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name_plural': 'Product Variants'},
        ),
    ]
