# Generated by Django 5.0 on 2024-02-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_code_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='code',
        ),
    ]
