# Generated by Django 5.0 on 2024-02-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_remove_color_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Material'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Dimension'},
        ),
    ]
