# Generated by Django 5.0 on 2024-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_color_options_alter_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=1, max_length=100, verbose_name='Product Tag'),
            preserve_default=False,
        ),
    ]
