# Generated by Django 5.0 on 2024-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_tag',
            field=models.CharField(blank=True, help_text='Do not fill or change this filed', max_length=600, null=True, verbose_name='Sensetive'),
        ),
    ]
