# Generated by Django 5.0 on 2024-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterField(
            model_name='usercart',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Product Color'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='price',
            field=models.FloatField(verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Product Size'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
    ]
