# Generated by Django 5.0 on 2024-02-08 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0031_alter_color_options_alter_size_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Contact Number')),
                ('division', models.CharField(max_length=50, verbose_name='Division')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.TextField(verbose_name='Address')),
                ('post_code', models.CharField(max_length=50, verbose_name='Post Code')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('total', models.FloatField(verbose_name='Total Payment')),
                ('payment_mode', models.CharField(max_length=250)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('order_status', models.CharField(default='Pending', max_length=250)),
                ('tracking_no', models.CharField(max_length=250, verbose_name='Tracking ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creating Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updating Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation')),
            ],
        ),
    ]
