# Generated by Django 5.0 on 2024-02-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
