# Generated by Django 5.0 on 2024-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_order_statuses_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Received'), ('S', 'Shipped'), ('D', 'Delivered')], default='Pending', max_length=250, verbose_name='Order Status'),
        ),
    ]
