# Generated by Django 5.0 on 2024-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=250, verbose_name='Order Status'),
        ),
    ]
