# Generated by Django 5.0 on 2024-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('is currently on pending', 'is currently on pending'), ('has been received', 'has been received'), ('is being shipped', 'is being shipped'), ('has been delivered', 'has been delivered')], default='is currently on pending', max_length=250, verbose_name='Order Status'),
        ),
    ]
