# Generated by Django 5.0 on 2024-01-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_adds_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
