# Generated by Django 5.0 on 2024-01-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_adds_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adds',
            old_name='Image1',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='adds',
            name='Image2',
        ),
    ]
