# Generated by Django 5.0 on 2024-01-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_image1_adds_image_remove_adds_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adds',
            old_name='Image',
            new_name='image',
        ),
    ]
