# Generated by Django 5.0 on 2024-02-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_rename_image_adds_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adds',
            options={'verbose_name_plural': 'Upload Image'},
        ),
    ]
