# Generated by Django 5.0 on 2024-02-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_adds_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adds',
            options={'verbose_name_plural': 'Upload Image For Advertisement'},
        ),
    ]
