# Generated by Django 5.0 on 2024-02-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_alter_adds_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adds',
            options={'verbose_name_plural': 'Home Page Advertisement'},
        ),
    ]
