# Generated by Django 5.0 on 2024-02-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_adds_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adds',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='adds',
            name='title',
        ),
    ]
