# Generated by Django 5.0 on 2024-01-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbackground',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_background', to='banner.banner'),
        ),
    ]
