# Generated by Django 5.0 on 2024-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_bannerbackground_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerbackground',
            name='title',
            field=models.CharField(default='I am another', max_length=50),
        ),
    ]
