# Generated by Django 5.0 on 2024-01-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_bannerbackground_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerbackground',
            name='title',
        ),
        migrations.AlterField(
            model_name='bannerbackground',
            name='banner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner_background', to='banner.banner'),
        ),
    ]
