# Generated by Django 5.0 on 2024-01-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_categorybanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryBanner',
        ),
    ]
