# Generated by Django 5.0 on 2024-01-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_delete_categorybanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerBackground',
        ),
    ]
