# Generated by Django 5.0 on 2024-02-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0010_banner_active_alter_banner_image_alter_banner_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Give name to the banner'),
        ),
    ]
