# Generated by Django 5.0 on 2024-02-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_rename_active_banner_is_active_alter_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
