# Generated by Django 5.0 on 2024-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=60, verbose_name='Cupon Code')),
                ('discount_percentage', models.FloatField(verbose_name='Discount Percentage')),
            ],
            options={
                'verbose_name_plural': 'Coupon Discount',
            },
        ),
    ]
