# Generated by Django 5.0 on 2024-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='uploads\\site_logo', verbose_name='Upload Site Logo')),
                ('welcome_message', models.CharField(max_length=600, verbose_name='Write Welcome Message')),
                ('facebook_link', models.CharField(max_length=600, verbose_name='Facebook Page Link')),
                ('instagram_link', models.CharField(max_length=600, verbose_name='Instagram Link')),
                ('twitter_link', models.CharField(max_length=600, verbose_name='Twitter Link')),
                ('fav_icon', models.ImageField(upload_to='uploads\\Favicon', verbose_name='Upload Fav Icon')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
