# Generated by Django 5.0 on 2024-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_settings',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/product_detail_advertisement_image', verbose_name='Upload Image (For advertisement on product detail page)'),
            preserve_default=False,
        ),
    ]
