# Generated by Django 5.0 on 2024-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default=1, upload_to='uploads/brand_logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='uploads/Vendor_banner', verbose_name='Vendor banner'),
        ),
    ]
