# Generated by Django 5.0 on 2024-01-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_logo_brand_short_description_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
