# Generated by Django 5.0 on 2024-01-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_phone_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='facebook_link',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram_link',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
