# Generated by Django 5.0 on 2024-01-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_brand_facebook_link_brand_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
