# Generated by Django 5.0 on 2024-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_brand_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Vendor Information'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(verbose_name='Add an ellaborate description abou the vendor'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='facebook_link',
            field=models.CharField(max_length=600, verbose_name='Facebook Profile Link'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram_link',
            field=models.CharField(max_length=600, verbose_name='Instagram Profile Link'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='location',
            field=models.CharField(max_length=600, verbose_name='Provide a detailed address of the vendor showroom'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='uploads/brand_logo', verbose_name='Vendor Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_description',
            field=models.TextField(verbose_name='Short Description About The Vendors'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name Of The Vendor'),
        ),
    ]
