# Generated by Django 5.0 on 2024-02-06 07:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_alter_brand_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brand Information'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Add an ellaborate description abou the Barnd'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='uploads/Vendor_banner', verbose_name='Barnd banner'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='location',
            field=models.CharField(max_length=600, verbose_name='Provide a detailed address of the Barnd showroom'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='uploads/brand_logo', verbose_name='Barnd Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_description',
            field=models.TextField(verbose_name='Short Description About The Barnd'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name Of Teh Barnd'),
        ),
    ]
