# Generated by Django 5.0 on 2024-02-28 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_alter_brand_options_alter_brand_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Add an ellaborate description about the Brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='uploads/Vendor_banner', verbose_name='Brand banner'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='location',
            field=models.CharField(max_length=600, verbose_name='Provide a detailed address of the Brand showroom'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='uploads/brand_logo', verbose_name='Brand Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_description',
            field=models.TextField(verbose_name='Short Description About The Brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name Of The Brand'),
        ),
    ]
